[bot]
name = "Your Bot Name"
owners = [123456789, 987654321]
default_language = "en"

[database]
max_connections = 5

[discord]
application_id = 123456789012345678

[features]
enable_music = false
enable_moderation = true
enable_custom_commands = false