[bot]
name = "Your Bot Name"
owners = [123456789, 987654321]
default_language = "en"

[database]
max_connections = 5

[discord]
application_id = 123456789012345678

[telemetry]
enabled = true
log_file = "telemetry.log"
batch_size = 100